=== JesusAlfredoCobosValencia/40260/xml/gramatica.dtd
<!ELEMENT lavadora (secuencia)>
<!ELEMENT secuencia (llenarAgua, lavar, repetir, centrifugar)>
<<<<<<< HEAD
<!ELEMENT llenarAgua EMPTY>
<!ELEMENT lavar EMPTY>
<!ELEMENT repetir (enjuagar)>
<!ATTLIST repetir veces CDATA #REQUIRED>
<!ELEMENT enjuagar EMPTY>
<!ELEMENT centrifugar EMPTY>
=======

<!ELEMENT llenarAgua EMPTY>
<!ELEMENT lavar EMPTY>

<!ELEMENT repetir (enjuagar, enjuagar)>
<!ATTLIST repetir veces CDATA #REQUIRED>

<!ELEMENT enjuagar EMPTY>
<!ELEMENT centrifugar EMPTY>
>>>>>>> cc58d2140e262f9a01a402f0b05aa9f661de3109

=== JesusAlfredoCobosValencia/40260/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lavadora SYSTEM "gramatica.dtd">
<<<<<<< HEAD
=======

>>>>>>> cc58d2140e262f9a01a402f0b05aa9f661de3109
<lavadora>
    <secuencia>
        <llenarAgua/>
        <lavar/>
        <repetir veces="2">
            <enjuagar/>
<<<<<<< HEAD
=======
            <enjuagar/>
>>>>>>> cc58d2140e262f9a01a402f0b05aa9f661de3109
        </repetir>
        <centrifugar/>
    </secuencia>
</lavadora>
