=== JesusAlfredoCobosValencia/40260/xml/xml-00.dtd
<<<<<<< HEAD
<?xml version="1.0" encodign="UTF-8"?>
<!ELEMENT direccion (nombrecompleto, correo, telefono, cumple)>
<!ELEMENT nombrecompleto (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
=======
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombreCompleto, correo, teleono, cumple)>
<!ELEMENT nombreCompleto(nombre, apellidos)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT apellidos(#PCDATA)>
<!ELEMENT correo(#PCDATA)>
<!ELEMENT telefono(#PCDATA)>
<!ELEMENT cumple(dia, mes, anio)>
<!ELEMENT dia(#PCDATA)>
<!ELEMENT mes(#PCDATA)>
<!ELEMENT aniA(#PCDATA)>
>>>>>>> cc58d2140e262f9a01a402f0b05aa9f661de3109

=== JesusAlfredoCobosValencia/40260/xml/xml-00.xml
<<<<<<< HEAD
<?xml version="1.0" encodign="UFT-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombrecompleto>
        <nombre>Rafael</nombre>
        <apellidos>R C</apellidos>
    </nombrecompleto>
    <correo>rrojano@uv.mx</correo>
    <telefono>1919139393</telefono>
    <cumple>
        <dia>1</dia>
        <mes>1</mes>
        <anio>1</anio>
    </cumple>
</direccion>
=======
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "">
<direccion>
    <nombreCompleto>
        <nombre> Rafael</nombre>
        <apellidos> R C</apellidos>
    </nombreCompleto>
    <correo>cobosj454@gmailcom</correo>
    <telefono> 911911911</telefono>
    <cumple> 
        <dia>1</dia>
        <mes>1</mes>
        <anio>1</anio> 
    </cumple>    
 </direccion>
>>>>>>> cc58d2140e262f9a01a402f0b05aa9f661de3109
